### ISSUE TITLE
Is it possible to conduct experiments using widely used benchmarks?

### ISSUE THREAD

**Issue by YKQ98** [usccolumbia/deeperGATGNN#4]
Is it possible to include results of deeperGATGNN for JARVIS-2021, MP-2018, or Matbench, such that researchers can have a better understanding of performance gains of deeperGATGNN?

**Comment by sadmanomee** [comment]
We will run those experiments and send those results to you. You can also give it a try using this repo. Just put the dataset in the data folder and create a targets.csv file following the format (unzip test_data from data folder to see a targets file format). Then you can run those experiments using the commands in the description.
