### ISSUE TITLE
process case of MOF_data

### ISSUE THREAD

**Issue by fei-wang-1314** [usccolumbia/deeperGATGNN#8]
Hi, how to process case of MOF_data with the process.py. At the line 7, mofs = ase.io.read('opt-geometries.xyz',index=':'), but what is opt-geometries.xyz? There is no this file in the qmof_database.
Thank you.

**Comment by sadmanomee** [comment]
I can email you the files. Or I can send you the dataset if you want.

**Comment by sadmanomee** [comment]
Let me know.

**Comment by fei-wang-1314** [comment]
> I can email you the files. Or I can send you the dataset if you want.

Thank you for help.
I have found the band gap file at 'https://figshare.com/articles/dataset/Ensemble_Band_Gap_Data/8295503?file=15544181'
For the two files:

  mofs = ase.io.read('opt-geometries.xyz',index=':')
  refcodes = np.genfromtxt('opt-refcodes.csv',delimiter=',',dtype=str)
using the file：cifs_to_xyz.py at https://github.com/arosen93/QMOF/tree/main/database_tools.

Are these steps correct?

**Comment by sadmanomee** [comment]
I am not sure whether they are exactly same.
