### ISSUE TITLE
t-sne question

### ISSUE THREAD

**Issue by Jbangliang** [usccolumbia/deeperGATGNN#9]
Hello,this is an awesome work.But I'm confused when i use the model 'Analysis' model.
![QQ图片20240528103242](https://github.com/usccolumbia/deeperGATGNN/assets/136157142/1b0e426a-e574-48c4-b063-087849b97696)
![QQ图片20240528103406](https://github.com/usccolumbia/deeperGATGNN/assets/136157142/65d5badc-6841-4feb-8873-87de20fd8409)

**Comment by sadmanomee** [comment]
That is happening because when you trained and saved the model, you probably did not use any post linear layer (post_fc_count is set to 0 by deafult for DeeperGATGNN in config.yml). So, post_lin_list[0] is showing out of index. Train another model with post_fc_count: 1 and then try the t-SNE. I hope the error will go away. Let me know if you need more help.

**Comment by Jbangliang** [comment]
Thank you for your response. This issue has been resolved. However, when I ran the code again, the following error occurred. I searched for it, and it seems to be related to multi-GPU usage. I only have one GPU for running the code. I set the parallel option in the project's config.yml file to false, but this doesn't seem to work.
![QQ图片20240604100635](https://github.com/usccolumbia/deeperGATGNN/assets/136157142/d7071853-7bea-4caa-8076-86e5b5a432de)

**Comment by Jbangliang** [comment]
I found the problem by searching. Thanks again for your help

**Comment by Jia-12138** [comment]
Thanks. I am experiencing some issues with the data. The data retrieved through scripts from the Materials Project database has been continuously updated, and it now differs from the data in your paper. Therefore, may I contact you via email to request your data? I would greatly appreciate it.

**Comment by Jbangliang** [comment]
Thanks. I am experiencing some issues with the data. The data retrieved through scripts from the Materials Project database has been continuously updated, and it now differs from the data in your paper. Therefore, may I contact you via email to request your data? I would greatly appreciate it.

**Comment by sadmanomee** [comment]
Yes, you can email me at omee.sadman@gmail.com

**Comment by Jbangliang** [comment]
Thank you

**Comment by Jia-12138** [comment]
s
